

app_brand:
    path: /brand
    controller: App\Controller\BrandController::Brands

app_color:
    path: /color
    controller: App\Controller\ColorController::Colors

app_category:
    path: /category
    controller: App\Controller\CategoryController::Category

app_product:
    path: /product
    controller: App\Controller\ProductController::Products

app_size:
    path: /size
    controller: App\Controller\SizeController::Sizes

app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_index:
    path: /index
    controller: App\Controller\IndexController::index

app_chaustore3:
    path: /chaustore3
    controller: App\Controller\Chaustore3Controller::index